language: go
go:
  - 1.10.x
  - master
addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

matrix:
  allow_failures:
    - go: master

notifications:
  email: false

install:
  - glide update
  - go get -u gopkg.in/alecthomas/gometalinter.v2 && gometalinter.v2 --install

script:
  - gometalinter.v2 --config .linter.json
  - go test -race ./...
